protected-mode no
bind 0.0.0.0
tls-port 6390
tls-cert-file /tls/test.crt
tls-key-file /tls/test.key
tls-ca-cert-file /tls/ca.crt
save ""
enable-debug-command yes
io-threads 10
io-threads-do-reads yes
appendonly no
